N2kyni contacts
jorijoo/product-store-assignment pull request #2
Opened 2023-11-21 10:35 UTC by timoasumaniemi

Remove links from text

2023-11-21 10:38 UTC, timoasumaniemi reviewed
Fix the commented links

2023-11-21 10:38 UTC, timoasumaniemi commented on src/common/components/Footer/Footer.js
>                  <a href="#" className="footer-link">
Remove links from text

2023-11-21 10:41 UTC, NicoK81 commented on src/common/components/Footer/Footer.js
>                  <a href="#" className="footer-link">
all good

2023-11-21 10:56 UTC, timoasumaniemi reviewed
good to go

2023-11-21 11:05 UTC, jorijoo requested changes
Check the comments in Footer.js

2023-11-21 11:05 UTC, jorijoo commented on src/common/components/Footer/Footer.js
> +                <a>
Change to divs instead of as

2023-11-21 11:05 UTC, jorijoo commented on src/common/components/Footer/Footer.js
> +                <a>
Div instead of a

2023-11-22 11:10 UTC, timoasumaniemi reviewed
I think the `daavidin_divari.jpg` file can be removed from the `public` folder. 
Otherwise should be good for merge.

2023-11-22 11:38 UTC, timoasumaniemi reviewed
Gg

2023-11-22 14:44 UTC, jorijoo approved these changes
All the changes are as requested, good job!

2023-11-22 15:36 UTC, merged