21 shopping cart display
jorijoo/product-store-assignment pull request #3
Opened 2023-11-22 12:46 UTC by laovirtanen

2023-11-22 16:04 UTC, jorijoo requested changes

2023-11-22 16:04 UTC, jorijoo commented on public/Group 6.png
Muuta tiedostojen nimet erikoismerkittömiksi (välilyönti). esim. group_6.png

2023-11-22 16:04 UTC, jorijoo commented on public/Group 7.png
Muuta tiedostojen nimet erikoismerkittömiksi (välilyönti). esim. group_6.png

2023-11-22 16:04 UTC, jorijoo commented on src/common/components/Cart/CartCard.js
> +  const displayImage = imageUrl || "placeholder-kuvan url";
Laita placeholder-kuvan url

2023-11-22 16:04 UTC, jorijoo commented on src/common/components/Cart/CartCard.js
> +  const closeIconUrl = "/Group 6.png";
Korjaa nää kuva-linkit erikoismerkittömään muotoon.

2023-11-22 16:07 UTC, laovirtanen commented on src/common/routes/Cart.js
> +  const [productsInCart, setProductsInCart] = useState([
> Dummy data tulee tässä vaiheessa korvata palvelimelta.
> 
> Axioksella: https://big.kapsi.fi/products

Ei kai ostoskorin sisältöä haeta backendistä?

2023-11-22 16:14 UTC, laovirtanen commented on src/common/routes/Cart.js
> +  const [productsInCart, setProductsInCart] = useState([
tai voihan sen hakea, mutta eikö se ole aika turhaa tässä kohtaa? pitäisi ensiksi olla mahdollisuus lisätä tuotteita ostoskoriin ylipäänsä ja tallentaa ne muuttujaan.

2023-11-22 16:25 UTC, laovirtanen commented on src/common/routes/Cart.js
> +  const [productsInCart, setProductsInCart] = useState([
täytyykö kutsuja tallentaa backendiin??

2023-11-22 16:31 UTC, laovirtanen commented on src/common/routes/Cart.js
> +  const [productsInCart, setProductsInCart] = useState([
Eli kun lisää tuotteen ostoskoriin productDetail komponentista, niin tallennetaan se suoraan ostoskorin tilamuuttujaan. Backendiä tarvitaan vain jos täytyy tallentaa jonkun käyttäjän ostoskorin tiedot pidemmäksi aikaa. Muuten varmaan pärjätään localstoragella?

2023-11-23 11:15 UTC, jorijoo commented on src/common/routes/Cart.js
> +  const [productsInCart, setProductsInCart] = useState([
Ostoskori siirtyy backendiin vasta tilausvaiheessa. Sellainen ominaisuus ei ole käytettävissä toistaiseksi.

Mutta puhuimme tuossa Timon kanssa, että jätetään backend-kutsujen laitto myöhemmäksi. Dummy-data on ok tällä hetkellä.

2023-11-23 12:33 UTC, timoasumaniemi requested changes
Koodit muuten ok, mutta merge conflict pitää korjata.
Eli:
-update mainista, RoutesComponent.js tiedostosta pitää yhdistää kummatkin mainin ja tämän branchin lisäykset.
-push edellä oleva korjaus tähän branchiin
-loppuvarmistus että korjaukset tuli tehtyä, sitten voi mergetä mainiin.

2023-11-23 12:41 UTC, timoasumaniemi approved these changes

2023-11-23 12:41 UTC, timoasumaniemi approved these changes

2023-11-23 12:47 UTC, merged